# Generated by Django 3.0.5 on 2020-06-04 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserDF',
        ),
    ]
